# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9533e9eae149e4731b9f01092fbfc644282dce19d7a66e47009434674f31e32d010f29e508558dd98c1ecff30daba95455bca2d205137ad3f0386bcf64b2aa56

test:
  secret_key_base: 39792c457640b817d4b8be3c5bf9cfaaef86a3f1218e122104d450e01e49017fc02049b49b16853e0f1a02dc348cd54b8bd10fe54dd5daa63eee48aaf573f0d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
